In [1]:
import numpy as np
import theano.tensor as T
from theano import function

In [3]:
x = T.dscalar("x")
y = T.dscalar("y")
z = x + y
f = function([x,y],z)

In [5]:
f(2,3)

array(5.0)

In [7]:
np.isclose(f(14.1, 22.3), 36.4)

array([ True], dtype=bool)

In [11]:
print(type(x))
print(x.type)
print(T.dscalar)
print(x.type is T.scalar)

<class 'theano.tensor.var.TensorVariable'>
TensorType(float64, scalar)
TensorType(float64, scalar)
False


In [13]:
from theano import pp
pp(z)

'(x + y)'

In [14]:
X = T.dmatrix("X")
Y = T.dmatrix("Y")
Z = X + Y
f = function([X,Y], Z)

In [17]:
print(f([[1,2],[3,4]],[[10,20],[30,40]]))
print(f(np.array([[1,2],[3,4]]),np.array([[10,20],[30,40]])))

[[ 11.  22.]
 [ 33.  44.]]
[[ 11.  22.]
 [ 33.  44.]]


In [34]:
a = T.vector()
b = T.vector()
out = a**2 + 2.*a*b + b**2
f = function([a, b], out)
print(f([1.], [1.])), pp(out)

[ 4.]


(None,
 '(((<TensorType(float64, vector)> ** TensorConstant{2}) + ((TensorConstant{2.0} * <TensorType(float64, vector)>) * <TensorType(float64, vector)>)) + (<TensorType(float64, vector)> ** TensorConstant{2}))')