In [1]:
import numpy as np
import theano.tensor as tt
import theano

In [4]:
r = tt.row()
print(r.broadcastable)
mtr = tt.matrix()
print(mtr.broadcastable)
f_row = theano.function([r, mtr], [r + mtr])
R = np.arange(3).reshape(1, 3)
print(R)
M = np.arange(9).reshape(3, 3)
print(M)
print(f_row(R,M))
c = tt.col()
print(c.broadcastable)
f_col = theano.function([c, mtr], [c + mtr])
C = R.T
print(C)
print(f_col(C, M))

(True, False)
(False, False)
[[0 1 2]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[array([[  0.,   2.,   4.],
       [  3.,   5.,   7.],
       [  6.,   8.,  10.]])]
(False, True)
[[0]
 [1]
 [2]]
[array([[  0.,   1.,   2.],
       [  4.,   5.,   6.],
       [  8.,   9.,  10.]])]
