In [1]:
import numpy as np
import theano.tensor as tt
import theano
from scipy import ndimage
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
im = ndimage.imread("data/david.jpg")
im = im[136:336, 49:449] # crop
print("Shape:", im.shape)
plt.imshow(im, cmap="gray")
plt.show()

In [83]:
# simple 2d convolution
# note the filter_flip flag is not the default, apparently this is called 
# a cross-correlation whereas True would be for convolutions.
X = tt.tensor4("X")
A = tt.tensor4("A")
y = tt.nnet.conv2d(X, A, input_shape=(1, 1, 5, 5), filter_shape=(1, 1, 3, 3), 
                   subsample=(1, 1), border_mode=(0,0), filter_flip=False)
f = theano.function([X, A], y)
x = np.array([[[[3, 3, 2, 1, 0], 
                [0, 0, 1, 3, 1],
                [3, 1, 2, 2, 3], 
                [2, 0, 0, 2, 2], 
                [2, 0, 0, 0, 1]]]])
a = np.array([[[[0, 1, 2],
                [2, 2, 0],
                [0, 1, 2]]]])
b = np.array([[[[0, 0, 0],
                [0, 0, 0],
                [0, 0, 1]]]])
c = np.array([[[[1, 0, 0],
                [0, 0, 0],
                [0, 0, 0]]]])
print(x.shape, a.shape)
print(x)
print(a)
print(f(x, a))


(1, 1, 5, 5) (1, 1, 3, 3)
[[[[3 3 2 1 0]
   [0 0 1 3 1]
   [3 1 2 2 3]
   [2 0 0 2 2]
   [2 0 0 0 1]]]]
[[[[0 1 2]
   [2 2 0]
   [0 1 2]]]]
[[[[ 12.  12.  17.]
   [ 10.  17.  19.]
   [  9.   6.  14.]]]]


In [97]:
X = tt.tensor4("X")
A = tt.tensor4("A")
Y = tt.nnet.conv2d(X, A, border_mode=(1, 1), subsample=(2, 2), 
                   input_shape=(1, 1, 5, 5), filter_shape=(1, 1, 3, 3),
                   filter_flip=False)
f = theano.function([X, A], Y)

# test values
x = np.array([[[[2, 2, 3, 3, 3], 
                [0, 1, 3, 0, 3],
                [2, 3, 0, 1, 3], 
                [3, 3, 2, 1, 2], 
                [3, 3, 0, 2, 3]]]])
a = np.array([[[[2, 0, 1],
                [1, 0, 0],
                [0, 1, 1]]]])
'''
The "answer" in the picture is incorrect
y = np.array([[[[1, 6, 5],
                [7, 10, 9],
                [7, 10, 8]]]])
'''
print(f(x, a))

[[[[  1.   5.   6.]
   [  7.   8.   3.]
   [  3.  10.   4.]]]]


Object `np.flip` not found.
